load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "greetings",
    srcs = ["src/greetings.cpp"],
    hdrs = ["include/greetings.h"],
    visibility = ["//visibility:public"],
)