# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      
      - name: Build and run tests
        run: bazel test //...

      - name: Zip and publish compponent
        run: git archive --format=tar.gz HEAD > component-a.tar.gz
        
      - name: Upload component
        uses: actions/upload-artifact@v4
        with:
          name: component-a
          path: component-a.tar.gz

      - run: ls

      - name: Create release
        run: gh release create 

      - name: Create release
        run: |
          gh release create v0.0.${{ github.sha }} --generate-notes
          gh release upload v0.0.${{ github.sha }} component-a.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
